[build]
  publish = "public"
  command = ""
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
[[headers]]
  for = "/**/*.html"
  [headers.values]
    Cache-Control = "public, max-age=60"
[[headers]]
  for = "/**/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
