name: Deploy Backend to Render
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy via deploy hook
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          test -n "$RENDER_DEPLOY_HOOK_URL" || { echo "Missing RENDER_DEPLOY_HOOK_URL secret"; exit 1; }
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK_URL"
          echo "Deploy triggered"
